#!/command/with-contenv bash
exit_code="${1:-0}"
if [[ "${exit_code}" -eq 256 ]]; then
  exit_code=$((128 + ${2:-0}))
fi
# Always restart the updater loop unless the container is stopping cleanly.
if [[ "${exit_code}" -eq 0 ]]; then
  exit 1
fi
sleep 30
exit 0
